Repository Global-Students/global-students-client, pull requests merged in 2024-02, with the labels that each got.

#22 Revert "Revert "#16 [FEAT] 아이디 및 비밀번호 찾기 뷰 구현 완료""
  src/App.js
  src/pages/FindAccount/FindAccountPage.jsx
  src/pages/FindAccount/FindId.jsx
  src/pages/FindAccount/FindPassword.jsx
  src/pages/Login.jsx
Labels: 희원👻, feat

#30 [FEAT] 로그인 기능 구현 완료
  .eslintrc.json
  package.json
  public/mockServiceWorker.js
  src/components/Input.jsx
  src/hooks/useLogin.jsx
  src/index.js
  src/mocks/browser.js
  src/mocks/handlers.js
  src/pages/Login.jsx
  yarn.lock
Labels: 희원👻, feat

#33 [FEAT] 회원가입 기능 구현 (학교 인증 제외)
  public/assets/key.svg
  public/assets/person.svg
  src/App.js
  src/apis/signUp.js
  src/assets/reset.svg
  src/components/Button/DuplicateCheckButton.jsx
  src/components/Button/ResetButton.jsx
  src/components/Input.jsx
  src/components/Input/BirthDayInput.jsx
  src/components/Input/Checkbox.jsx
  src/components/Input/DuplicateCheckInput.jsx
  src/components/Input/Input.jsx
  src/components/Input/ResetButtonInput.jsx
  src/components/ResetIcon.jsx
  src/components/ValidationMessage.jsx
  src/constants/api.js
  src/constants/date.js
  src/constants/index.js
  src/constants/regex.js
  src/constants/signUpForm.js
  src/mocks/handlers.js
  src/pages/FindAccount/FindId.jsx
  src/pages/FindAccount/FindPassword.jsx
  src/pages/Login.jsx
  src/pages/SignUp.jsx
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUpInfo.jsx
  src/pages/SignUp/TermsAndPrivacy.jsx
  src/pages/SignUp/Welcome.jsx
  src/pages/SignUpInfo.jsx
  tailwind.config.js
Labels: 희원👻, feat

#34 #24 [FEAT] 아이디 및 비밀번호 찾기 기능 구현
  package.json
  src/apis/findAccount.js
  src/constants/api.js
  src/constants/regex.js
  src/mocks/handlers.js
  src/pages/FindAccount/FindId.jsx
  src/pages/FindAccount/FindPassword.jsx
Labels: 희원👻, feat

#36 #31 [FEAT] 관리자 페이지 사이드바 & 회원목록 & 학교승인 뷰 구현 완료
  src/App.js
  src/components/Button/ManagementButton.jsx
  src/components/SearchBox.jsx
  src/components/SideBar.jsx
  src/components/Table/MemberListTable.jsx
  src/components/Table/UniversityApprovalTable.jsx
  src/constants/dummy.js
  src/constants/id.js
  src/constants/index.js
  src/constants/schema.js
  src/pages/Admin/AdminPage.jsx
  src/pages/Admin/MemberListPage.jsx
  src/pages/Admin/UniversityApprovalPage.jsx
  tailwind.config.js
Labels: 희원👻, feat

#38 [FEAT] 검색 헤더 뷰 구현 완료
  public/assets/close.svg
  public/assets/close_small.svg
  public/assets/group.svg
  public/assets/help.svg
  public/assets/searchInBox.svg
  src/App.js
  src/assets/bubbleName.svg
  src/components/DropDown.jsx
  src/components/Header.jsx
  src/components/Header/FindSchoolBox.jsx
  src/components/Header/Header.jsx
  src/components/Header/HeaderIcon.jsx
  src/components/Header/RealTimePopularPosts.jsx
  src/components/Header/SearchHeader.jsx
  src/components/Input/SearchInput.jsx
  src/components/LoginControl.jsx
  src/components/PopularList.jsx
  src/components/Posts.jsx
  src/components/SearchInput.jsx
  src/components/UserInfoControl.jsx
  tailwind.config.js
Labels: 지희🦄, feat

#44 #23 [FEAT] 회원가입에 학교 인증 기능 추가
  package.json
  public/assets/error.svg
  public/assets/success.png
  src/apis/signUp.js
  src/assets/outgoingMail.svg
  src/assets/uploadFile.svg
  src/components/Button/AuthButton.jsx
  src/components/Button/DuplicateCheckButton.jsx
  src/components/Button/LightOrangeButton.jsx
  src/components/Button/OrangeButton.jsx
  src/components/Button/ResetButton.jsx
  src/components/Button/WhiteButton.jsx
  src/components/CheckForm.jsx
  src/components/Input/BirthDayInput.jsx
  src/components/Input/Checkbox.jsx
  src/components/Input/FileInput.jsx
  src/components/Input/Input.jsx
  src/components/Input/LightOrangeButtonInput.jsx
  src/components/Input/OptionInput.jsx
  src/components/Modal.jsx
  src/components/ValidationMessage.jsx
  src/constants/api.js
  src/constants/index.js
  src/constants/signUpForm.js
  src/contexts/SignUpContext.jsx
  src/mocks/handlers.js
  src/pages/Login.jsx
  src/pages/SignUp/EmailApproval.jsx
  src/pages/SignUp/FileApproval.jsx
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUpInfo.jsx
  src/pages/SignUp/TermsAndPrivacy.jsx
  src/pages/SignUp/UniversityApproval.jsx
  tailwind.config.js
Labels: 희원👻, feat

#47 #24 [FEAT] 비밀번호 재설정 구현 완료
  src/apis/findAccount.js
  src/constants/api.js
  src/mocks/handlers.js
  src/pages/FindAccount/FindAccountPage.jsx
  src/pages/FindAccount/FindPassword.jsx
  src/pages/FindAccount/PasswordReset.jsx
  src/utils/checkPattern.js
Labels: 희원👻, feat

#46 #40 [FEAT] RefreshToken으로 AccessToken 재발급 구현
  src/apis/findAccount.js
  src/axios/authAxios.js
  src/constants/api.js
  src/hooks/useLogin.jsx
  src/mocks/handlers.js
Labels: 희원👻, feat

#49 #48 [FEAT] 로그인 API 에러 핸들링
  src/constants/api.js
  src/hooks/useLogin.jsx
  src/mocks/handlers.js
Labels: 희원👻, feat

#50 #45 [FEAT] 로그아웃 구현
  src/constants/api.js
  src/hooks/useLogout.jsx
  src/mocks/handlers.js
Labels: 희원👻, feat

#54 #51 [FEAT] Access token 재발급 API 에러 핸들링
  src/axios/authAxios.js
  src/mocks/handlers.js
Labels: 희원👻, feat

#57 #41 [FEAT] 검색 결과 뷰 구현 완료
  public/assets/arrow_forward_ios.svg
  public/assets/manage_search.svg
  src/App.js
  src/components/DropDown.jsx
  src/components/Header.jsx
  src/components/Header/SearchHeader.jsx
  src/components/Input/SearchInput.jsx
  src/components/PostList.jsx
  src/components/Posts.jsx
  src/components/SearchList.jsx
  src/components/SearchText.jsx
  src/constants/boardName.js
  src/pages/Search/Search.jsx
  src/pages/Search/SearchDetailListPage.jsx
  src/pages/Search/SearchListPage.jsx
Labels: 지희🦄, feat

#58 #55 [REFACTOR] 회원가입 페이지 에러 핸들링
  src/apis/signUp.js
  src/hooks/useSignUp.jsx
  src/mocks/handlers.js
  src/pages/SignUp/EmailApproval.jsx
  src/pages/SignUp/SignUpInfo.jsx
  src/pages/SignUp/UniversityApproval.jsx
Labels: 희원👻, feat

#61 #59 [FEAT] 아이디 및 비밀번호 찾기 API 에러 핸들링
  src/apis/findAccount.js
  src/components/Button/FindAccountButton.jsx
  src/hooks/useFindPassword.jsx
  src/mocks/handlers.js
  src/pages/FindAccount/FindAccountPage.jsx
  src/pages/FindAccount/FindId.jsx
  src/pages/FindAccount/FindPassword.jsx
  src/pages/FindAccount/PasswordReset.jsx
Labels: 희원👻, feat

#63 #62 [RENAME] useFindPassword.jsx를 useFindAccount.jsx로 파일명 변경
  src/hooks/useFindAccount.jsx
  src/pages/FindAccount/FindId.jsx
  src/pages/FindAccount/FindPassword.jsx
  src/pages/FindAccount/PasswordReset.jsx
Labels: 희원👻, refactor

#65 #64 [ADD] ValidationMessage 컴포넌트의 success 아이콘 대체
  public/assets/success.png
  public/assets/success.svg
  src/components/Input/FileInput.jsx
  src/components/ValidationMessage.jsx
Labels: 희원👻, refactor

#68 #67 [REFACTOR] login() 인터페이스 수정
  src/hooks/useLogin.jsx
  src/pages/Login.jsx
Labels: 희원👻, refactor

#69 #66 [MODIFY] 회원가입 페이지 기타 기능 수정
  src/constants/belongTo.js
  src/constants/file.js
  src/constants/index.js
  src/hooks/useSignUp.jsx
  src/pages/SignUp/EmailApproval.jsx
  src/pages/SignUp/FileApproval.jsx
  src/pages/SignUp/SignUpInfo.jsx
  src/pages/SignUp/UniversityApproval.jsx
Labels: 희원👻, modify

#73 #71 [CHORE] Noto sans 폰트 추가 및 react-i18next 라이브러리 추가
  .eslintrc.json
  package.json
  src/index.css
  src/index.js
  src/locales/en/translation.json
  src/locales/i18n.js
  src/locales/ko/translation.json
  yarn.lock
Labels: 희원👻, chore

#29 #26 [FEAT] 개인정보 수정 페이지 뷰 구현 완료
  package-lock.json
  public/assets/lock.svg
  public/assets/lock_hover.svg
  public/assets/unlock.svg
  public/assets/unlock_hover.svg
  src/App.js
  src/components/Button/AccessToggle.jsx
  src/components/Button/uploadImage.jsx
  src/components/Input/InfoInput.jsx
  src/components/Input/LongInput.jsx
  src/pages/Update/UpdateInfo.jsx
  src/pages/Update/UpdateProfile.jsx
  yarn.lock
Labels: 채은😎, feat

#32 #11 [FEAT] 마이페이지 뷰 구현 완료
  src/App.js
  src/assets/ellipse-28.png
  src/assets/rectangle-88.png
  src/components/Button/PrivacyButton.jsx
  src/components/Infobox.jsx
  src/components/PageNavigation.jsx
  src/components/PostTable.jsx
  src/components/ProfileBox.jsx
  src/pages/BookmarkPosts.jsx
  src/pages/DashBoard.jsx
  src/pages/MyPage.jsx
  src/pages/MyPosts.jsx
  yarn.lock
Labels: 채은😎, feat

#76 #75 [FIX] i18n.js 경로 오타 수정 및 ESLint 에러 해결
  .eslintrc.json
  src/locales/i18n.js
Labels: 희원👻, fix

#78 #77 [REFACTOR] PostList 컴포넌트 table 수정 완료
  src/components/PostList.jsx
Labels: 지희🦄, refactor

#81 #79 [REFACTOR] SearchList 컴포넌트 오류, 검색 결과 화면 수정 사항 반영하여 수정 완료
  src/App.js
  src/components/DropDown.jsx
  src/components/Header/FindSchoolBox.jsx
  src/components/Header/SearchHeader.jsx
  src/components/Input/SearchInput.jsx
  src/components/SearchList.jsx
  src/components/SearchText.jsx
  src/pages/Search/SearchDetailListPage.jsx
Labels: 지희🦄, refactor

#82 #70 [REFACTOR] 회원가입 기타 기능 개선
  src/assets/error.svg
  src/assets/success.svg
  src/components/ValidationMessage.jsx
  src/constants/date.js
  src/mocks/handlers.js
  src/pages/SignUp/SignUpInfo.jsx
Labels: 희원👻, refactor

#60 #28 [FEAT] 커뮤니티 게시판 기능 구현 완료
  package.json
  public/assets/photo.svg
  public/mockServiceWorker.js
  src/components/Button/ShowButton.jsx
  src/components/DropDown.jsx
  src/components/Header/RealTimePopularPosts.jsx
  src/components/Header/SearchHeader.jsx
  src/components/Inform.jsx
  src/components/Pagination.jsx
  src/components/PopularList.jsx
  src/components/PostList.jsx
  src/components/Posts.jsx
  src/constants/api.js
  src/mocks/board.json
  src/mocks/handlers.js
  src/mocks/searchPop.json
  src/pages/NoticeBoard.jsx
  tailwind.config.js
  yarn.lock
Labels: 지희🦄, feat

#87 #86 [REFACTOR] PopularList 컴포넌트 스타일 수정
  src/components/PopularList.jsx
Labels: 지희🦄, refactor

#89 [FEAT] 푸터 수정 및 각 항목에 대한 뷰 구현 완료
  public/assets/arrow_back.svg
  public/assets/arrow_back_ios.svg
  public/assets/arrow_back_ios_orange.svg
  public/assets/closeButton.svg
  src/App.js
  src/components/Button/CloseButton.jsx
  src/components/DropDownInquiry.jsx
  src/components/Footer.jsx
  src/components/Input/InquiryInputBox.jsx
  src/components/InquiryInput.jsx
  src/constants/privacyPolicy.js
  src/pages/Footer/Inquiry.jsx
  src/pages/Footer/PrivacyPolicy.jsx
  src/pages/NoticeBoard.jsx
Labels: 지희🦄, feat

#95 #94 [FEAT] 로그인 필요한 서비스 라우트 보호
  src/App.js
  src/hooks/useLogout.jsx
  src/index.js
  src/pages/App.jsx
  src/pages/NotFound.jsx
  src/pages/ProtectedRoute.jsx
  src/pages/Routes.jsx
Labels: 희원👻, feat

#97 #96 [FIX] Notice Board에서 새로고침 시 Access token이 복구되는 현상 수정 완료
  src/axios/authAxios.js
Labels: 희원👻, fix

#101 #100 [REFACTOR] 로그인 정보를 전역으로 관리
  src/contexts/AuthContext.jsx
  src/index.js
  src/pages/ProtectedRoute.jsx
Labels: 희원👻, refactor

#99 #98 [REFACTOR] 라우트 이름 변경
  src/components/Button/ShowButton.jsx
  src/components/Header.jsx
  src/components/Infobox.jsx
  src/components/LoginControl.jsx
  src/components/SearchListItem.jsx
  src/components/SideBar.jsx
  src/components/UserInfoControl.jsx
  src/constants/id.js
  src/constants/index.js
  src/pages/DashBoard.jsx
  src/pages/MyPage.jsx
  src/pages/Routes.jsx
  src/pages/SignUp/Welcome.jsx
  src/pages/Update/UpdateInfo.jsx
  src/pages/Update/UpdateProfile.jsx
Labels: 희원👻, refactor

#108 #107 [FIX] Header 컴포넌트 오류 수정, NoticeBoard axios로 변경
  src/components/Header/Header.jsx
  src/pages/NoticeBoard.jsx
Labels: 지희🦄, refactor, fix

#109 [REFACTOR] 커뮤니티 게시판 기능 구현 수정 및 헤더 기능 구현 수정
  src/components/Header/Header.jsx
  src/components/InformText.jsx
  src/components/PostList.jsx
  src/components/Posts.jsx
  src/mocks/board.json
  src/pages/NoticeBoard.jsx
Labels: 지희🦄, refactor

#112 #111 [REFACTOR] NoticeBoard 컴포넌트 수정 완료
  src/components/BottomPost.jsx
  src/pages/NoticeBoard.jsx
Labels: 지희🦄, refactor

#114 #113 [CORRECT] 로그인 박스에서 계정 찾기와 회원가입 링크에 연결된 라우트를 케밥 케이스로 수정
  src/pages/Login.jsx
Labels: 희원👻, feat

#116 #115 [FIX] 회원가입 완료 페이지 내 정보 채우러 가기 버튼에 연결된 라우트 수정
  src/pages/SignUp/Welcome.jsx
Labels: 희원👻, fix

#118 #117 [REFACTOR] NoticeBoard 재수정 완료
  src/pages/NoticeBoard.jsx
Labels: 지희🦄, refactor

#119 #102 API 연결
  package.json
  public/mockServiceWorker.js
  src/axios/authAxios.js
  src/components/Header/Header.jsx
  src/constants/signUpForm.js
  src/contexts/AuthContext.jsx
  src/contexts/SignUpContext.jsx
  src/hooks/useFindAccount.jsx
  src/hooks/useLogin.jsx
  src/hooks/useLogout.jsx
  src/hooks/useSignUp.jsx
  src/index.js
  src/pages/FindAccount/FindPassword.jsx
  src/pages/NoticeBoard.jsx
  src/pages/ProtectedRoute.jsx
  yarn.lock
Labels: 희원👻, feat

#120 #105 [FEAT] 통합 검색 기능 구현
  src/components/DropDown.jsx
  src/components/Header/FindSchoolBox.jsx
  src/components/Header/Header.jsx
  src/components/Header/RealTimePopularPosts.jsx
  src/components/Header/SearchHeader.jsx
  src/components/Input/SearchInput.jsx
  src/components/Pagination.jsx
  src/components/PostList.jsx
  src/components/Posts.jsx
  src/components/SearchList.jsx
  src/components/SearchResultsDropdown.jsx
  src/components/SearchText.jsx
  src/constants/boardName.js
  src/hooks/useSearchList.jsx
  src/mocks/handlers.js
  src/mocks/totalSearch.json
  src/mocks/univSearch.json
  src/pages/NoticeBoard.jsx
  src/pages/Routes.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/SearchDetailListPage.jsx
  src/pages/Search/SearchListPage.jsx
Labels: 지희🦄, feat

#128 #127 [MODIFY] 회원가입 기능 수정
  src/axios/authAxios.js
  src/contexts/SignUpContext.jsx
  src/hooks/useSignUp.jsx
  src/index.js
  src/pages/SignUp/EmailApproval.jsx
  src/pages/SignUp/UniversityApproval.jsx
Labels: 희원👻, modify

#135 #130 [FEAT] 로그아웃 기능, 로그아웃 버튼에 연결
  src/components/UserInfoControl.jsx
  src/hooks/useLogout.jsx
Labels: 희원👻, feat

#137 #134 [MODIFY] 비밀번호 재설정 메서드 변경
  src/hooks/useFindAccount.jsx
  src/mocks/handlers.js
Labels: 희원👻, modify

#140 [FEAT] 글작성 데이터 연결
  src/components/Header/Header.jsx
  src/components/Inform.jsx
  src/components/Pagination.jsx
  src/components/PopularList.jsx
  src/components/Posts.jsx
  src/hooks/useLogin.jsx
  src/pages/NoticeBoard.jsx
  src/pages/Post/Dropdown1.jsx
  src/pages/Post/PostCreate.jsx
Labels: 희원👻, feat

#141 #138 [FEAT] 댓글 익명 기능 추가
  src/components/Comment.jsx
  src/components/WriteComment.jsx
  src/pages/Post/PostView.jsx
Labels: 희원👻, feat

#142 #126 [FEAT] 게시글 삭제 API 연결
  src/components/CheckboxPost.jsx
  src/components/MoreDropdown.jsx
  src/pages/Post/PostCreate.jsx
  src/pages/Post/PostUpdate.jsx
  src/pages/Post/PostView.jsx
Labels: 희원👻, 현준🐻, feat

#143 #124 [FEAT] 게시글 수정 API 연결 완료
  src/components/MoreDropdown.jsx
  src/pages/Post/PostUpdate.jsx
Labels: 희원👻, 현준🐻, feat

#144 #132 [FEAT] 댓글 삭제 API 연결
  src/components/WriteComment.jsx
  src/pages/Post/PostView.jsx
Labels: 희원👻, 현준🐻, feat

#146 #145 [MODIFY] 회원가입 대학교 및 국가 드롭 리스트 값 수정
  src/constants/belongTo.js
  src/pages/SignUp/SignUpInfo.jsx
Labels: 희원👻, modify

#148 #147 [MODIFY] 이용약관, 개인정보보호동의, 마케팅 홍보 스크립트 수정
  src/constants/index.js
  src/constants/signUpForm.js
Labels: 희원👻, modify

#150 #149 [MODIFY] 학교 리스트 수정
  src/constants/belongTo.js
Labels: 희원👻, modify
